version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pbr
    versions:
    - 5.5.1
