default_language_version:
  python: python3.7

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["-l", "80"]
-   repo: https://github.com/PyCQA/bandit
    rev: "2421df6"
    hooks:
      - id: bandit
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
      - id: check-json
      - id: requirements-txt-fixer
