language: python
sudo: false
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- pypy
- pypy3
install:
- pip install -r requirements/base.txt
- pip install -r requirements/tests.txt
- python setup.py install
script:
- py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing
- py.test tests/functional/
after_script:
- pep8 --show-source pad
after_success:
- coveralls
